### PR TITLE
Added small validation to ensure the popup shows up at the right moment.

### PR DESCRIPTION
**Pull request by bubudrc**
Because the rating prompt will always show up when a debugger is attached, I added an small validation to shows up when the app is running on DEBUG configuration

### CODE REVIEW

**Comment by mezhevikin** [comment]
Hey Marcelo.  Thanks for the pull-request.  But you are mistaken, the prompt is shown only once, regardless of whether it is a debug or a release.  You can run unittests and see for yourself.

https://github.com/mezhevikin/AppReview/blob/master/Tests/AppReviewTests/AppReviewTests.swift#L10

**Comment by bubudrc** [comment]
Hi,
hmmm.. I tested on my own app, and in debug mode, if I call `AppReview().requestIfNeeded()`, I'm always got the alert.

I [rec a video to confirm the changes works ok](https://we.tl/t-MuCFNNmC83)

**Comment by mezhevikin** [comment]
@bubudrc It is very interesting. Because, before request() I set [lastReviewDate](https://github.com/mezhevikin/AppReview/blob/master/Sources/AppReview/AppReview.swift#L67), and next time var [isNeeded](https://github.com/mezhevikin/AppReview/blob/master/Sources/AppReview/AppReview.swift#L58) should return false. 

I don't have idea yet what is wrong.
Can you search "SKStoreReviewController" in Xcode project?
Perhaps you forget remove other calls of this method?

**Comment by mezhevikin** [comment]
Try print lastReviewDate and isNeeded after and before request:

```
let review = AppReview()
print("\(review.lastReviewDate) \(review.isNeeded)")
review.requestIfNeeded()
print("\(review.lastReviewDate) \(review.isNeeded)")
```

**Comment by bubudrc** [comment]
I'm ignoring that. If you check the code 
`guard !isDebugConfig else {
             request()
             return true
         }`
it's on top, so, I'm calling to `request()` and ignoring the rest.

**Comment by bubudrc** [comment]
Didn't liked my PR? 🤔

**Pull request closed without merging**
